
services:
  python-api:
    build: .
    container_name: python-api
    networks:
      - mongodb-net
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mongodb-net
    ports:
      - "27017:27017"

networks:
  mongodb-net:
    driver: bridge
