FROM python:3.12-alpine

WORKDIR /opt/python-monitor/

RUN mkdir -p ./volumes/logs

COPY monitor_script.py /opt/python-monitor/

RUN pip install --no-cache-dir requests

CMD ["python", "/opt/python-monitor/monitor_script.py"]